#!/usr/bin/env python3
"""Project canonical agent skills into the Codex and Claude discovery trees."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import sys
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

try:
    import yaml
except ModuleNotFoundError:
    yaml = None


REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_ROOT = REPO_ROOT / "agent-skills" / "skills"
CLAUDE_AGENTS_ROOT = REPO_ROOT / ".claude" / "agents"
PROJECTIONS = {
    "codex": REPO_ROOT / ".agents" / "skills",
    "claude": REPO_ROOT / ".claude" / "skills",
}
SHARED_CLAUDE_ADAPTERS = {"content-extractor", "content-qa", "gap-filler"}
LEGACY_CODEX_FILES = [
    REPO_ROOT / ".codex" / "prompts" / "audit-cosmetic-permabuffs.md",
]
MANIFEST_NAME = ".agent-skills-projection.json"
MANIFEST_SCHEMA = 1
MANIFEST_GENERATOR = "tools/sync_agent_skills.py"
GENERATED_NOTICE = (
    "<!-- Generated by tools/sync_agent_skills.py from agent-skills/skills. "
    "Do not edit this projection. -->"
)
NAME_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
HASH_PATTERN = re.compile(r"^[0-9a-f]{64}$")
RETIRED_REFERENCES = {
    "$ARGUMENTS",
    "TODO.md",
    "HANDOFF_ACQUIRED_TEMPLATES.md",
    "PERMABUFF_FIX_QUEUE.md",
    ".codex/prompts/",
}


@dataclass(frozen=True)
class ProjectedFile:
    content: bytes
    mode: int = 0o644


def require_yaml() -> None:
    if yaml is None:
        raise RuntimeError(
            "PyYAML is required; run: "
            "uv run --isolated --with-requirements "
            "tools/requirements-agent-skills.txt python tools/sync_agent_skills.py"
        )


def load_yaml_mapping(path: Path, text: str) -> dict[str, object]:
    require_yaml()
    try:
        parsed = yaml.safe_load(text)
    except yaml.YAMLError as error:
        raise ValueError(f"{path}: invalid YAML: {error}") from error
    if not isinstance(parsed, dict):
        raise ValueError(f"{path}: YAML must be a mapping")
    if not all(isinstance(key, str) for key in parsed):
        raise ValueError(f"{path}: YAML keys must be strings")
    return parsed


def parse_frontmatter(
    path: Path, content: str, *, portable: bool = True
) -> tuple[list[str], list[str], dict[str, object]]:
    lines = content.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{path}: Markdown must start with YAML frontmatter")
    try:
        closing = lines.index("---", 1)
    except ValueError as error:
        raise ValueError(f"{path}: YAML frontmatter is not closed") from error

    frontmatter = lines[1:closing]
    metadata = load_yaml_mapping(path, "\n".join(frontmatter))
    if portable and set(metadata) != {"name", "description"}:
        raise ValueError(
            f"{path}: canonical frontmatter must contain only name and description"
        )
    if portable:
        name = metadata["name"]
        description = metadata["description"]
        if not isinstance(name, str) or name != path.parent.name:
            raise ValueError(f"{path}: skill name must match its directory")
        if not NAME_PATTERN.fullmatch(name):
            raise ValueError(f"{path}: skill name {name!r} is not portable")
        if not isinstance(description, str) or not description.strip():
            raise ValueError(f"{path}: description must be a non-empty string")

    return frontmatter, lines[closing + 1 :], metadata


def render_skill(skill_dir: Path, platform: str) -> bytes:
    skill_path = skill_dir / "SKILL.md"
    content = skill_path.read_text(encoding="utf-8")
    frontmatter, body, _ = parse_frontmatter(skill_path, content)
    body_text = "\n".join(body)
    for retired in RETIRED_REFERENCES:
        if retired in body_text:
            raise ValueError(f"{skill_path}: references retired material {retired!r}")

    platform_lines: list[str] = []
    overlay = skill_dir / "platforms" / f"{platform}.frontmatter"
    if overlay.exists():
        platform_text = overlay.read_text(encoding="utf-8")
        platform_metadata = load_yaml_mapping(overlay, platform_text)
        if {"name", "description"} & set(platform_metadata):
            raise ValueError(f"{overlay}: overlay cannot replace portable frontmatter")
        if "argument-hint" in platform_metadata and not isinstance(
            platform_metadata["argument-hint"], str
        ):
            raise ValueError(f"{overlay}: argument-hint must be a string")
        platform_lines = platform_text.splitlines()

    combined = [*frontmatter, *platform_lines]
    load_yaml_mapping(skill_path, "\n".join(combined))
    rendered = ["---", *combined, "---", GENERATED_NOTICE, *body]
    return ("\n".join(rendered).rstrip() + "\n").encode("utf-8")


def expected_projection(platform: str) -> dict[Path, ProjectedFile]:
    expected: dict[Path, ProjectedFile] = {}
    skill_dirs = sorted(path for path in SOURCE_ROOT.iterdir() if path.is_dir())
    if not skill_dirs:
        raise ValueError(f"no canonical skills found under {SOURCE_ROOT}")

    for skill_dir in skill_dirs:
        skill_name = skill_dir.name
        skill_path = skill_dir / "SKILL.md"
        if not skill_path.is_file():
            raise ValueError(f"{skill_dir}: missing SKILL.md")

        openai_path = skill_dir / "agents" / "openai.yaml"
        if not openai_path.is_file():
            raise ValueError(f"{skill_dir}: missing agents/openai.yaml")
        openai_metadata = load_yaml_mapping(
            openai_path, openai_path.read_text(encoding="utf-8")
        )
        interface = openai_metadata.get("interface")
        if not isinstance(interface, dict):
            raise ValueError(f"{openai_path}: missing interface mapping")
        default_prompt = interface.get("default_prompt")
        if not isinstance(default_prompt, str) or f"${skill_name}" not in default_prompt:
            raise ValueError(
                f"{openai_path}: default_prompt must name ${skill_name}"
            )

        expected[Path(skill_name) / "SKILL.md"] = ProjectedFile(
            render_skill(skill_dir, platform)
        )
        for source in sorted(skill_dir.rglob("*")):
            if not source.is_file() or source.name == "SKILL.md":
                continue
            relative = source.relative_to(skill_dir)
            if relative.parts[0] == "platforms":
                continue
            if platform == "claude" and relative == Path("agents/openai.yaml"):
                continue
            expected[Path(skill_name) / relative] = ProjectedFile(
                source.read_bytes(), stat.S_IMODE(source.stat().st_mode)
            )
    return expected


def validate_claude_adapters() -> None:
    if not CLAUDE_AGENTS_ROOT.exists():
        return
    for name in sorted(SHARED_CLAUDE_ADAPTERS):
        adapter = CLAUDE_AGENTS_ROOT / f"{name}.md"
        if not adapter.is_file():
            raise ValueError(f"{adapter}: shared-skill adapter is missing")
        _, body_lines, metadata = parse_frontmatter(
            adapter, adapter.read_text(encoding="utf-8"), portable=False
        )
        if metadata.get("name") != name:
            raise ValueError(f"{adapter}: adapter name must be {name!r}")
        if not (SOURCE_ROOT / name / "SKILL.md").is_file():
            raise ValueError(f"{adapter}: no canonical {name!r} skill exists")
        skills = metadata.get("skills")
        if not isinstance(skills, list) or name not in skills:
            raise ValueError(f"{adapter}: adapter must preload the {name!r} skill")
        body = "\n".join(line for line in body_lines if line.strip())
        canonical_path = f"agent-skills/skills/{name}/"
        if canonical_path not in body or len(body.splitlines()) > 3:
            raise ValueError(
                f"{adapter}: adapters must be thin pointers to {canonical_path}"
            )


def sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def expected_hashes(expected: dict[Path, ProjectedFile]) -> dict[Path, str]:
    return {relative: sha256(projected.content) for relative, projected in expected.items()}


def manifest_content(expected: dict[Path, ProjectedFile]) -> bytes:
    files = {
        relative.as_posix(): digest
        for relative, digest in sorted(expected_hashes(expected).items())
    }
    payload = {
        "schema": MANIFEST_SCHEMA,
        "generator": MANIFEST_GENERATOR,
        "files": files,
    }
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


def validate_relative_path(value: str, manifest_path: Path) -> Path:
    pure = PurePosixPath(value)
    if pure.is_absolute() or not pure.parts or any(part in {"", ".", ".."} for part in pure.parts):
        raise ValueError(f"{manifest_path}: unsafe generated path {value!r}")
    return Path(*pure.parts)


def load_manifest(root: Path) -> dict[Path, str] | None:
    manifest_path = root / MANIFEST_NAME
    if not manifest_path.exists():
        return None
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"{manifest_path}: invalid ownership manifest: {error}") from error
    if not isinstance(payload, dict) or payload.get("schema") != MANIFEST_SCHEMA:
        raise ValueError(f"{manifest_path}: unsupported ownership manifest")
    if payload.get("generator") != MANIFEST_GENERATOR:
        raise ValueError(f"{manifest_path}: unrecognized manifest generator")
    files = payload.get("files")
    if not isinstance(files, dict):
        raise ValueError(f"{manifest_path}: files must be a mapping")

    parsed: dict[Path, str] = {}
    for value, digest in files.items():
        if not isinstance(value, str) or not isinstance(digest, str):
            raise ValueError(f"{manifest_path}: file paths and hashes must be strings")
        if not HASH_PATTERN.fullmatch(digest):
            raise ValueError(f"{manifest_path}: invalid hash for {value!r}")
        parsed[validate_relative_path(value, manifest_path)] = digest
    return parsed


def safe_destination(root: Path, relative: Path) -> Path:
    destination = root / relative
    resolved_root = root.resolve()
    resolved_destination = destination.resolve(strict=False)
    if not resolved_destination.is_relative_to(resolved_root):
        raise ValueError(f"refusing to follow projection path outside {root}: {relative}")
    return destination


def check_projection(
    platform: str, root: Path, expected: dict[Path, ProjectedFile]
) -> list[str]:
    problems: list[str] = []
    expected_digests = expected_hashes(expected)
    for relative, projected in sorted(expected.items()):
        destination = safe_destination(root, relative)
        if not destination.is_file():
            problems.append(f"{platform}: missing {relative}")
        elif destination.read_bytes() != projected.content:
            problems.append(f"{platform}: stale {relative}")

    ownership = load_manifest(root)
    if ownership is None:
        problems.append(f"{platform}: missing {MANIFEST_NAME}")
        return problems
    for relative in sorted(set(expected_digests) - set(ownership)):
        problems.append(f"{platform}: ownership manifest missing {relative}")
    for relative in sorted(set(ownership) - set(expected_digests)):
        problems.append(f"{platform}: ownership manifest contains stale {relative}")
    for relative in sorted(set(ownership) & set(expected_digests)):
        if ownership[relative] != expected_digests[relative]:
            problems.append(f"{platform}: ownership hash stale for {relative}")
    return problems


def atomic_write(destination: Path, projected: ProjectedFile) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.tmp")
    temporary.write_bytes(projected.content)
    os.chmod(temporary, projected.mode)
    os.replace(temporary, destination)


def write_projection(
    root: Path,
    expected: dict[Path, ProjectedFile],
    *,
    allow_unowned_overwrite: bool,
) -> list[Path]:
    root.mkdir(parents=True, exist_ok=True)
    ownership = load_manifest(root) or {}
    stale = sorted(set(ownership) - set(expected), reverse=True)

    # Preflight every mutation before writing anything.
    for relative, projected in expected.items():
        destination = safe_destination(root, relative)
        if not destination.exists():
            continue
        if not destination.is_file():
            raise ValueError(f"{destination}: expected a file")
        current = destination.read_bytes()
        if current == projected.content:
            continue
        if relative in ownership and sha256(current) != ownership[relative]:
            raise ValueError(f"{destination}: refusing to overwrite a modified generated file")
        if (
            relative not in ownership
            and not allow_unowned_overwrite
            and GENERATED_NOTICE.encode("utf-8") not in current
        ):
            raise ValueError(f"{destination}: refusing to overwrite an unowned file")

    for relative in stale:
        destination = safe_destination(root, relative)
        if not destination.exists():
            continue
        if not destination.is_file():
            raise ValueError(f"{destination}: refusing to delete a non-file")
        if sha256(destination.read_bytes()) != ownership[relative]:
            raise ValueError(f"{destination}: refusing to delete a modified generated file")

    for relative, projected in sorted(expected.items()):
        destination = safe_destination(root, relative)
        if destination.exists() and destination.read_bytes() == projected.content:
            os.chmod(destination, projected.mode)
            continue
        atomic_write(destination, projected)

    removed: list[Path] = []
    for relative in stale:
        destination = safe_destination(root, relative)
        if destination.exists():
            destination.unlink()
            removed.append(relative)
        parent = destination.parent
        while parent != root:
            try:
                parent.rmdir()
            except OSError:
                break
            parent = parent.parent

    atomic_write(root / MANIFEST_NAME, ProjectedFile(manifest_content(expected)))
    return removed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="report projection drift without changing files"
    )
    parser.add_argument(
        "--platform",
        action="append",
        choices=tuple(PROJECTIONS),
        help="limit the operation to one projection (repeatable; defaults to both)",
    )
    parser.add_argument(
        "--projection-root",
        type=Path,
        help="write/check one selected platform at an alternate root",
    )
    parser.add_argument(
        "--adopt-existing",
        action="store_true",
        help="allow a one-time overwrite of colliding files not yet in an ownership manifest",
    )
    args = parser.parse_args()

    selected_platforms = args.platform or list(PROJECTIONS)
    if args.projection_root is not None and len(selected_platforms) != 1:
        parser.error("--projection-root requires exactly one --platform")
    if args.check and args.adopt_existing:
        parser.error("--adopt-existing cannot be combined with --check")
    roots = dict(PROJECTIONS)
    if args.projection_root is not None:
        roots[selected_platforms[0]] = args.projection_root.resolve()

    try:
        require_yaml()
        validate_claude_adapters()
        expected = {
            platform: expected_projection(platform) for platform in selected_platforms
        }
        if args.check:
            problems = [
                problem
                for platform in selected_platforms
                for problem in check_projection(platform, roots[platform], expected[platform])
            ]
            if "codex" in selected_platforms and args.projection_root is None:
                problems.extend(
                    f"codex: legacy prompt remains at {path.relative_to(REPO_ROOT)}"
                    for path in LEGACY_CODEX_FILES
                    if path.exists()
                )
            if problems:
                print("Agent skill projections are out of date:", file=sys.stderr)
                for problem in problems:
                    print(f"  - {problem}", file=sys.stderr)
                print("Run: python3 tools/sync_agent_skills.py", file=sys.stderr)
                return 1
            counts = ", ".join(
                f"{platform}: {len(expected[platform])} files"
                for platform in selected_platforms
            )
            print(f"Agent skill projections are current ({counts}).")
            return 0

        for platform in selected_platforms:
            root = roots[platform]
            removed = write_projection(
                root,
                expected[platform],
                allow_unowned_overwrite=args.adopt_existing,
            )
            try:
                displayed_root = root.relative_to(REPO_ROOT)
            except ValueError:
                displayed_root = root
            print(f"Updated {platform} projection at {displayed_root}")
            for relative in removed:
                print(f"  removed stale generated file: {relative}")

        if "codex" in selected_platforms and args.projection_root is None:
            for legacy_file in LEGACY_CODEX_FILES:
                if legacy_file.exists():
                    legacy_file.unlink()
                    print(f"Removed legacy Codex prompt: {legacy_file.relative_to(REPO_ROOT)}")
        return 0
    except (OSError, RuntimeError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
